### ISSUE TITLE
Tooltip discrepancy

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1012]
The documentation of components that use the `sl-tooltip-enabled` mixin say that the `popover` property requires the `title` property.  And *tests/integration/components/sl-button-test.js* tests it this way, but

* *tests/integration/components/sl-progress-bar-test.js*
* *tests/integration/components/sl-textarea-test.js*
* *tests/integration/components/sl-tooltip-test.js*

do not set the `title` property and the tests pass just fine.

Also review

* *tests/integration/components/sl-alert-test.js*
* *tests/integration/components/sl-button-test.js*
* *tests/integration/components/sl-checkbox-test.js*
* *tests/integration/components/sl-drop-button-test.js*
for conformity.

**Comment by SpikedKira** [comment]
the tooltip component requires title; the tooltip mixin does not. Still looking into the rest of this

**Comment by erangeles** [comment]
@SpikedKira been working on this since last friday...as per my stand up status reports.

**Comment by erangeles** [comment]
@notmessenger @SpikedKira was assigned to this even though we established I was going to work on it last friday per our discussion on jabber.

**Comment by notmessenger** [comment]
@SpikedKira See all the components that https://github.com/softlayer/sl-ember-components/issues/1080 affects, which is related to this work/conversation, etc.  Does the related PR for this issue affect enough files?

**Comment by SpikedKira** [comment]
Thank you for pointing out that I missed some.
