### ISSUE TITLE
Invalid CSS property declaration at: *

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1035]
Occurs in this CSS declaration:

```
.select2-container {
    display: inline-block;
    height: auto !important;
    margin: 0;
    padding: 0;
    position: relative;
    * display: inline;
    /* inline-block for ie7 */
    vertical-align: middle;
    zoom: 1;
}
```

on the `* display: inline;` line.

Experienced this on Safari Version 9.0 (10601.1.56.2) on OS X Yosemite 10.10.5 (14F27)

**Comment by SpikedKira** [comment]
we can just remove that line as we don't support IE7.
Although, the space between "*" and "display" is likely introduced from LESS and may go away once we move to including the Select2 css directly as an include/import instead of forcing the Select2 styles inside of our own files.

**Comment by notmessenger** [comment]
Has been resolved by https://github.com/softlayer/sl-ember-components/pull/1136, as long as the `v0.11.0` is released (which it should be)
