### ISSUE TITLE
Demo app doesn't like being in a "narrower" browser window

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#11]
/#/sl-chart specifically. There is a sweet spot between where it will render correctly and where the chart is extremely large and the template examples never appear.

Don't know if this is something within the component styles itself or if its something about how we have our styles setup for the demo.

**Comment by SpikedKira** [comment]
this happens b/c we have improperly used bootstrap grid system in our demo app.
we have a single row with 2 divs "col-sm-6" and "col-lg-6".

reference: http://getbootstrap.com/css/#grid-example-mixed

It is okay to use both sm and lg on the same row, but all columns in the row should have both prefixes like the linked example.
