### ISSUE TITLE
Reconcile filter pane styles with new implementations

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1140]
https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/app/styles/sl-filter.less

**Comment by SpikedKira** [comment]
100% pointless as we do not offer a default filter component at this point.  This would introduce styles for things that do not exist (effectively guessing what the consuming application would use)

**Comment by azizpunjani** [comment]
@notmessenger @SpikedKira Does this need to be closed?
