### ISSUE TITLE
Make determination on class name to use on components

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1143]
`sl-ember-components` like in `sl-alert` since "alert" is a Bootstrap thing vs `sl-menu` on `sl-menu` since this is a non-Bootstrap component.

**Comment by notmessenger** [comment]
`sl-chart` needs to have `sl-ember-components` class applied so that loading mask is correctly picked up from `sl-panel` implementation

**Comment by SpikedKira** [comment]
So I think they should all have "sl-ember-components" and to attach styles to say alert, we could do ".sl-ember-components.alert {}" so that we target the sl-ember-component version of bootstrap alert.  The only issue I see is that we have some components that do not wrap a bootstrap component, like menu.  So something like menu would need two classes, and I am unsure what that second one should be.

**Comment by SpikedKira** [comment]
alert would not need sl-alert, as it has "alert" per bootstrap.  I think giving menu the class "menu" is not a great idea, but alert is already pretty generic as well and that's a bootstrap thing so our users already live with that one.

**Comment by SpikedKira** [comment]
We have begun moving to this pattern.  Example: pagination. "pagination sl-ember-components".

I think this is the right move.  We should maybe document possible class name collisions  to handle the case of things like "grid".

**Comment by notmessenger** [comment]
When this is decided, the documentation of each component should have a section added to it highlighting the specific selectors(s) that can be used for styling.  That can certainly be done individual issues but adding this not here so that it is not forgotten.  The README.md already makes mention of this existence so if not implemented then need to update the README.md

**Comment by notmessenger** [comment]
This PR - https://github.com/softlayer/sl-ember-components/pull/1433 - and this issue - https://github.com/softlayer/sl-ember-components/issues/1387 - address this issue.
