### ISSUE TITLE
Add inline support

### ISSUE THREAD

**Issue by SpikedKira** [softlayer/sl-ember-components#1156]
#sl-checkbox
#style
#v0.11.0

see sl-radio and bootstrap docs

**Comment by notmessenger** [comment]
@SpikedKira Is this a duplicate of https://github.com/softlayer/sl-ember-components/issues/1148 or something different?

**Comment by SpikedKira** [comment]
1148 applies to radio, this is for checkbox, the functionality is plainly missing.  radio had the functionality but needed a small fix.

**Comment by SpikedKira** [comment]
um, there's a PR for this, not sure why it didn't auto-link

**Comment by SpikedKira** [comment]
https://reviewable.io/reviews/softlayer/sl-ember-components/1162
