### ISSUE TITLE
Review DocBlock tag in uses of warn()

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1169]
Some say that an assertion is thrown.  is the the case when `warn()` is called?  make sure the docblock matches up with the logic of methods utilizing `warn()`

**Comment by juwara0** [comment]
I am working on this

**Comment by juwara0** [comment]
@notmessenger: We have usage of warn( 'message' ) from the utils which is Ember.Logger.warn( message ) and Ember.warn (message, test, options)

**Comment by juwara0** [comment]
@notmessenger: We could use @throws {ember/Logger.warn} and @throws {ember.warn} for these different cases.

**Comment by juwara0** [comment]
@notmessenger:
Here are the Ember implementations for each of the different cases:

Ember.warn()
https://github.com/emberjs/ember.js/blob/v2.2.0/packages/ember-debug/lib/warn.js#L26

Ember.Logger.warn()
https://github.com/emberjs/ember.js/blob/v2.2.0/packages/ember-metal/lib/logger.js#L76

**Comment by juwara0** [comment]
I am not sure if @throws is the correct usage but I did not see anything that looked like it might work better.  http://usejsdoc.org

**Comment by juwara0** [comment]
@notmessenger: There are no longer any uses of the warn() method including a definition in the docBlock header. This issue can be closed.
