### ISSUE TITLE
Change approach in Brocfile.js

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#118]
Per http://www.ember-cli.com/#environment-specific-assets, the include currently must be wrapped in an if statement checking for the environment.

Should replace current approach used.

**Comment by erangeles** [comment]
@notmessenger taking this.

**Comment by erangeles** [comment]
@notmessenger issue #74 addresses this I believe.

**Comment by notmessenger** [comment]
@erangeles Agreed.
