### ISSUE TITLE
bind to resize event for column header widths

### ISSUE THREAD

**Issue by SpikedKira** [softlayer/sl-ember-components#1182]
setupColumnHeaderWidths needs to be adjusted to run the function on didInsertElement, but also on window resize, using jquery.bind/on 

#aziz
#sl-grid

**Comment by SpikedKira** [comment]
obsolete when #1217 is merged

**Comment by SpikedKira** [comment]
should be obsolete now

**Comment by notmessenger** [comment]
@SpikedKira Should be or is?

**Comment by SpikedKira** [comment]
function no longer exists.  This failed logic has been removed entirely and this issue can be closed.
