### ISSUE TITLE
Put fonts in namespace

### ISSUE THREAD

**Issue by joshforisha** [softlayer/sl-ember-components#119]
https://github.com/softlayer/sl-ember-components/blob/develop/index.js#L52-L73

Shouldn't have to be putting them in their own root level /fonts directory that then has to be merged into the trees

should be in /sl-ember-components folder like with images, etc

**Comment by juwara0** [comment]
https://github.com/softlayer/sl-ember-components/blob/develop/index.js#L52-L73
Shouldn't have to be putting them in their own root level /fonts directory that then has to be merged into the trees
should be in /sl-ember-components folder like with images, etc
