### ISSUE TITLE
Take advantage of LESS nesting

### ISSUE THREAD

**Issue by azizpunjani** [softlayer/sl-ember-components#1194]
In some of our less files we take advantage of nesting i.e sl-input.less, in others we do not e.g sl-button.less, sl-menu.less and sl-tab-panel.less. We should take advantage of this less feature to keep code better organized and consistent across files. 

Migrating to sass should not be an issue specifically for nesting as less and sass both follow same nesting rules.

**Comment by notmessenger** [comment]
Keep in mind the work we want to achieve in [milestone v1.1.0](https://github.com/softlayer/sl-ember-components/milestones/v1.1.0%20(Smallest%20footprint%20possible)) and make sure that the structure will not hinder our ability to extract just the styling declarations needed on a per-component basis.

**Comment by SpikedKira** [comment]
mine

**Comment by SpikedKira** [comment]
actually, @azizpunjani is apparently doing this

**Comment by azizpunjani** [comment]
@notmessenger please assign to me, will do this while I'm doing the class work.
