### ISSUE TITLE
Replace arrow icon with "thinner" version

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1202]
Once https://github.com/softlayer/sl-ember-components/issues/1201 is completed.

**Comment by SpikedKira** [comment]
drop-button currently uses bootstrap helper class "caret" it should be moved over to a class of "sl-icon-" and given a glyph.  We have decided that glyph should be one in the 200-250 range, not currently available.

**Comment by SpikedKira** [comment]
depends on #1201

**Comment by SpikedKira** [comment]
desired glyph should now be available
