### ISSUE TITLE
Two copies of the same font are placed in the sl-ember-components/assets/fonts folder when fingerprinting is used

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1212]
Have attempted to employ this code to address this issue:

```
    /**
     * Copy Twitter Bootstrap fonts into namespaced assets folder
     *
     * @param {String} type
     * @param {Object} tree
     * @returns {Object}
     */
    postprocessTree: function( type, tree ) {
        var supportedTypes = [ 'eot', 'svg', 'ttf', 'woff' ];
        var supportedTypesLength = supportedTypes.length;
        var fontsToInclude = [];
        var containsAnyFontCheckingFor = function( extensions ) {
            var contains = false;

            for ( var i = 0; i < supportedTypesLength; i++ ) {
                if ( -1 !== extensions.indexOf( supportedTypes[i] ) ) {
                    contains = true;
                    break;
                }
            }

            return contains;
        }

        // Specifically-fingerprinted fonts
        if ( this.options &&
             this.options.fingerprint &&
             this.options.fingerprint.enabled &&
             containsAnyFontCheckingFor( this.options.fingerprint.extensions )
        ) {
            for ( var i = 0; i < supportedTypesLength; i++ ) {
                var pattern;

                if ( -1 !==  this.options.fingerprint.extensions.indexOf( supportedTypes[i] ) ) {
                    pattern = new RegExp( 'glyphicons-halflings-regular-[\d|\D]+\.' + supportedTypes[i], 'g' )

                } else {
                    pattern = new RegExp( 'glyphicons-halflings-regular\.' + supportedTypes[i] );
                }

                fontsToInclude.push( pattern );
            }
        } else {
            fontsToInclude.push( /glyphicons-halflings-regular/ );
        }

        var fonts = new Funnel( 'bower_components/bootstrap', {
            srcDir: 'fonts',
            destDir: this.name + '/assets/fonts',
            include: fontsToInclude
        });

        return mergeTrees(
            [
                tree,
                fonts
            ],
            {
                overwrite: true
            }
        );
    }
```

This code aims to only move the fingerprinted copies of the files for those that have been tagged to be fingerprinted and the non-fingerprinted ones for those that haven't, opposed to a copy of each being moved.

The problem having with this approach is that the regex filtering done by [broccoli funnel](https://github.com/broccolijs/broccoli-funnel) is not giving the expected results.  Passing the pattern of `glyphicons-halflings-regular-[\d|\D]+\.svg` to the `include` option of a broccoli funnel will not grab a file with the name of `glyphicons-halflings-regular-32941d6330044744c02493835b799e90.svg` but passing the value of `glyphicons-halflings-regular"` will, while `glyphicons-halflings-regular-` will not?

`"glyphicons-halflings-regular-32941d6330044744c02493835b799e90.svg".match(/glyphicons-halflings-regular-[\d|\D]+\.svg/)` works fine, so the regex is correct.

Stefan Penner recommended adding a test case in the broccoli funnel test suite to demonstrate the problem, which will also be a good way to isolate it from anything else.  This will demonstrate whether it's a problem with the library or our use of it.

There may be a better [a better hook](https://github.com/ember-cli/ember-cli/blob/master/ADDON_HOOKS.md) than can be employed.  That has not been explored yet.

**Comment by notmessenger** [comment]
Perhaps importing in `included()` would resolve this.  See https://github.com/miguelcobain/ember-leaflet/blob/master/index.js#L9-L21 for guidance.

**Comment by juwara0** [comment]
@notmessenger: I am taking a look at this.
