### ISSUE TITLE
"Integration | Component | sl grid: Setting height property gives the grid a fixed height" test failing in browser

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1226]

**Comment by SpikedKira** [comment]
can't verify this on my own since failure does not happen on windows

someone please check this or start from here:
https://github.com/SpikedKira/sl-ember-components/tree/issue-1226

**Comment by notmessenger** [comment]
@SpikedKira still fails

```
Expected: 	
1000

Result: 	
999

Diff: 	
1000999
```

**Comment by notmessenger** [comment]
Presently suspect a rounding error in the test (based on platform/browser) is causing this.

**Comment by notmessenger** [comment]
Not presenting itself in Windows but is on OS X

**Comment by notmessenger** [comment]
When I do a brand new clone and clean install of this repo on my local machine the tests pass.  When doing the same thing our our shared dev server that several other devs involved with the repo have access to this test fails.  Same browser, same OS, same code.  No other dev is experiencing this same issue.  So while I am certainly puzzled by it I am going to designate this issue us unreproducible until which time it might not be.
