### ISSUE TITLE
Documentation update: sl-calender's demo model is not in sync with demo model template

### ISSUE THREAD

**Issue by erangeles** [softlayer/sl-ember-components#1233]
demo model: https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/dummy/app/routes/demos/sl-calendar.js

demo template: https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/dummy/app/templates/demos/sl-calendar.hbs

**Comment by juwara0** [comment]
@notmessenger: I am working this
