### ISSUE TITLE
sl-select background color

### ISSUE THREAD

**Issue by azizpunjani** [softlayer/sl-ember-components#1243]
The current sl-select background color is one that we use to indicate that an input is disabled, when in fact it is enabled.

![image](https://cloud.githubusercontent.com/assets/156746/11628795/9cf224d2-9cb9-11e5-924c-828ae460ac4f.png)

![image](https://cloud.githubusercontent.com/assets/156746/11628780/8c71cb9e-9cb9-11e5-93dd-0663cd379ebf.png)

**Comment by SpikedKira** [comment]
This is a conflict with select2 and bootstrap.  Consider applying fix here: https://fk.github.io/select2-bootstrap-css/

**Comment by azizpunjani** [comment]
@notmessenger please assign this to me.
