### ISSUE TITLE
further implement sl-input typeahead component testing

### ISSUE THREAD

**Issue by erangeles** [softlayer/sl-ember-components#1247]
methods to test:
      `setupTypeahead()` [source](https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/addon/components/sl-input.js#L121)

arguements to test:
       `source` [source](https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/addon/components/sl-input.js#L144)
       `displayKey` [source](https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/addon/components/sl-input.js#L136)

typeahead events to test:
       `typeahead:autocomplete` [source](https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/addon/components/sl-input.js#L177)
       `typeahead:select` [source](https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/addon/components/sl-input.js#L178)

**Comment by notmessenger** [comment]
@erangeles Does this issue represents tests that need to exist but do not?  I am not clear on the focus of this issue.
