### ISSUE TITLE
Build fails due to updated Highcharts dependency

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1248]
The latest release of Highcharts is no longer installing the library files to the root of the *bower_components* folder but now instead inside of the *bower_components/lib* folder.  The included path in *index.js* need to be updated to reflect this.

**Comment by notmessenger** [comment]
Do this work against master, as it will be released as a bug-fix release.

**Comment by juwara0** [comment]
@notmessenger: I am looking at this

**Comment by alxyuu** [comment]
shouldn't the dependency version be updated to ~4.1.10 as well?

**Comment by notmessenger** [comment]
@alxyuu Agreed - https://github.com/softlayer/sl-ember-components/pull/1278
