### ISSUE TITLE
Keyboard shortcuts not working correctly in menu demo

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#130]

**Comment by jonathandavidson** [comment]
More specifically, numbered keys trigger the menu items to expand in reverse order. (i.e. Entering "1" expands the far right menu in lieu of the far left, etc.)

**Comment by notmessenger** [comment]
I have been able to determine that this problem appears with the inclusion of Ember 1.8.1+  Using version 1.7.1 or prior results in the menu working as expected.

**Comment by notmessenger** [comment]
Is due to this change - https://github.com/emberjs/ember.js/blob/v1.8.0/CHANGELOG.md:

[BREAKING] Ember.View didInsertElement is now called on child views before their parents. Before 1.8.0-beta.1 it would be called top-down.
