### ISSUE TITLE
Hide row Actions button if no actions are present

### ISSUE THREAD

**Issue by BryanCrotaz** [softlayer/sl-ember-components#139]
We filter our actions dropdown by using current user's rights. If that results in an empty list, it seems sensible to hide the actions dropdown.

```
// sl-grid-table-cell-actions.hbs
{{#if row.actionsButton}}
  {{sl-drop-button label="Actions" content=row.actionsButton theme="hover" target=targetObject}}
{{/if}}
```

**Comment by notmessenger** [comment]
Closed by https://github.com/softlayer/sl-ember-components/pull/344
