### ISSUE TITLE
Fix styles in demo application

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1418]
Have lost the icons in in the drop down and at the bottom of the page, as these are from Font Awesome which has been removed from the addon as a dependency.  If there are comparable Glyph icons can use that is fine, otherwise consider loading Font Awesome from CDN for use in the dummy app, or perhaps make use of [https://github.com/martndemus/ember-cli-font-awesome](https://github.com/martndemus/ember-cli-font-awesome)

**Comment by SpikedKira** [comment]
mine
