### ISSUE TITLE
Add content to Built in Icon Support page

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1419]
https://github.com/softlayer/sl-ember-components/wiki/Built-in-Icon-Support

**Comment by azizpunjani** [comment]
@SpikedKira this is in the v0.11.0 milestone, just making sure we don't forget about it.

**Comment by SpikedKira** [comment]
Not forgotten.  Unsure if still needed based on the current content of the readme file.  Do we still need to add content here?  If so, what should be included?

**Comment by notmessenger** [comment]
@SpikedKira We had a conversation about the content, where we were going to talk about the reasoning things were/had to be approached they way they were.  Think this was to include us to trampling on other classes, but not certain that was the specific topic or if it was limited to that.  When we discussed it I did not capture any of my thoughts.

**Comment by azizpunjani** [comment]
I have added some content to the Wiki. Please let me know if anything needs to be addd/modified. https://github.com/softlayer/sl-ember-components/wiki/Built-in-Icon-Support

**Comment by notmessenger** [comment]
@azizpunjani Great, thanks!
