### ISSUE TITLE
Create instructions on swapping base font

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1420]

**Comment by notmessenger** [comment]
@SpikedKira There aren't any special steps that need to be taken to accomplish beyond the ones you would normally take when using Twitter Bootstrap, right?  I'm not sure there is anything I need to add to the README about this.

**Comment by SpikedKira** [comment]
this is for the textual font and not the glyphs font, correct?  If so, you are correct.
However, something came up in verbal conversation a couple weeks ago.  We need to revisit LESS variable overriding and whether that's really possible or not for consuming applications.  I think that probably applies here.

**Comment by notmessenger** [comment]
@SpikedKira I'm going to close this issue then, as it does apply to the textual font, but do you want to open an issue or begin a conversation in Gitter regarding the other conversation topic you allude to?
