### ISSUE TITLE
Deprecation thrown in testing suite console.

### ISSUE THREAD

**Issue by erangeles** [softlayer/sl-ember-components#1439]
2 occurrences: DEPRECATION: Calling Ember.get without a target object has been deprecated, please specify a target object.

**Comment by notmessenger** [comment]
@erangeles Which tests is this occurring in?  https://travis-ci.org/softlayer/sl-ember-components/jobs/105032555 is the latest build of the v0.11.0 branch and no such errors are occurring.

**Comment by notmessenger** [comment]
It is at http://localhost:4200/tests

**Comment by erangeles** [comment]
@notmessenger happening in ```tests/integration/components/sl-grid-cell-test.js``` , addressed in https://github.com/erangeles/sl-ember-components/commit/a4db4b62c3404269f7057a5d2cc0ee6f03058e2c

**Comment by juwara0** [comment]
@erangeles - I am not able to reproduce the errors that you are seeing in this issue. One thing you may or may not know is that running these two commands is not the same:

ember serve then looking at http://localhost:4200/tests  (this one runs in the development environment)

vs.

ember test (this one runs in the test environment)

**Comment by SpikedKira** [comment]
deprecation verified locally in firefox

**Comment by erangeles** [comment]
steps to recreate. 

- ```git pull``` on v0.11.0 branch in sl-ember-components repo to gather latest changes
- ```ember server```
- visit ```/tests``` (let all tests run) and open console 

screenshot:

![Image of screenshot]
(http://imgur.com/HNOZhMY)

**Comment by juwara0** [comment]
@erangeles I am finally seeing what you reported.
