### ISSUE TITLE
Is this file even being used anymore?

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1445]
*tests/dummy/app/templates/demos/index.hbs*

* If not, delete it.
* If it is, where it it being linked to/from?  It's content needs to be updated.  Inform @notmessenger if it is being used.

**Comment by juwara0** [comment]
@notmessenger -The tests/dummy/app/templates/demos/index.hbs file is still in use and is link to from the drop down on each page by clicking on the "Demo" list item. It is also available by clicking the "Demo" link at the bottom of the "Home" demo app page.
