### ISSUE TITLE
Verify that the instructions for changing the icon font are still valid

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1447]
https://github.com/softlayer/sl-ember-components/tree/v0.11.0#icons compared to reference to fonts in the `.sl-ember-components-icons` declaration in *addons.less*

**Comment by erangeles** [comment]
@juwara0 please assign me this.

**Comment by azizpunjani** [comment]
@erangeles please read my [comment](https://github.com/softlayer/sl-ember-components/issues/1466#issuecomment-186296488) on icon classes issue. The instructions should stay the same I believe, as we will not be changing the icon classes to be dynamic.

**Comment by erangeles** [comment]
@notmessenger please close this as icon classes will not be dynamic
