### ISSUE TITLE
There's a new version of ember-sinon

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1464]

**Comment by juwara0** [comment]
Right now we are using "ember-sinon": "0.2.1". We are a couple of versions behind (https://github.com/csantero/ember-sinon/releases). In release 0.3.0, QUnit support is removed and this addon is abstracted to be used with QUnit in https://github.com/elwayman02/ember-sinon-qunit. There are a few things to consider in the usage section: https://github.com/elwayman02/ember-sinon-qunit#usage. Do we want to:

```
import { moduleFor } from 'ember-qunit';
import test from 'my-app/tests/ember-sinon-qunit/test';
```
or
```
import { moduleFor, test } from 'ember-qunit';
import sinonTest from 'my-app/tests/ember-sinon-qunit/test';
```

**Comment by notmessenger** [comment]
Have upgraded `ember-sinon` to latest release in https://github.com/softlayer/sl-ember-components/issues/1465
