### ISSUE TITLE
Evaluate if icon classes in the less files/templates need/can be namespaced

### ISSUE THREAD

**Issue by azizpunjani** [softlayer/sl-ember-components#1466]
Currently we provide the consuming application the option of changing the class prefix for component classes. Would we like to extend that to icons? If so, this would entail that classes such as `sl-close-icon` would be dynamically generated and a helper would need to be created for the templates to be able to generate a dynamic class name.

**Comment by azizpunjani** [comment]
@notmessenger please assign this to me.

**Comment by azizpunjani** [comment]
# Prefixing icon classes
This issue is a question and research phase to see if it's feasible and also a good idea to dynamically prefix
icon classes *and* the base icon class i.e `.sl-ember-components-icons`.

So `.sl-icon-close` would turn into `.sl-ember-components-icon-close` or `.custom-prefix-icon-close` if a prefix was set, and the
base icon class `.sl-ember-components-icons` would turn into `.custom-prefix-icons` if a prefix was set.

#### Background

Within `addon.less` we have a `.sl-ember-components-icons` class, with common (base) properties that pertain to all icons used in the addon:

```
.sl-ember-components-icons {
    width: 1.4em;
    display: inline-block;
    line-height: 1;
    vertical-align: middle;
    box-sizing: border-box;
    overflow: hidden;
    ....
}
```

This classes' properties are later [extended](http://lesscss.org/features/#extend-feature) into other icon classes
e.g in `app/styles/sl-pagination.less`.

```
.sl-icon-previous, .sl-icon-next {
    &:extend( .sl-ember-components-icons all );
}
```

To change an icon on the pagination component, such as the next icon, the end user would
write the following CSS:

```
.sl-ember-components-pagination .sl-icon-next::before {
    content: "\e258"; // override default icon
}
```

#### Why should we prefix?
The main reason for prefixing is for consistency. Currently we prefix the component class e.g `.sl-ember-components-[component-name]`, this would lead
one to think that the icon classes and base icon class would follow the same
convention.

### Why shouldn't we prefix?
Currently we use a dynamic LESS variable `component-class-prefix` used as shown
in the code below:
```
.@{component-class-prefix}-pagination {
    ...
}
```

If we try to apply the same dynamic variable technique to how we currently extend base icon properties, LESS does not support the syntax, as shown below:

```
.sl-icon-previous, .sl-icon-next {
    &:extend( .@{component-class-prefix}-icons all );
}
```

The docs state:
> Extend is NOT able to match selectors with variables. If selector contains variable, extend will ignore it.

Hence it's currently not possible to pass in dynamic class names to `:extend`.

Prefixing icon classes is also problematic. Let's assume we could prefix icon classes. Changing an icon within a component would now look like this, which is too verbose of a selector.

```
.sl-ember-components-pagination .sl-ember-components-icon-next::before {
    content: "\e258"; // override default icon
}
```

### Conclusion

##### Prefixing the base class `.sl-ember-components-icons`
Prefixing the base class is currently not supported by LESS because of limitations to LESS `:extend(..)`

##### Prefixing icon classes
Prefixing icon classes while might be possible with some extra work, is too verbose and would be cumbersome
for the user to type out if they do not provide a custom prefix. If they were to provide a custom prefix, then
the selector ends up being redundant.

**Comment by azizpunjani** [comment]
@notmessenger @juwara0 please read my [comment](https://github.com/softlayer/sl-ember-components/issues/1466#issuecomment-186296488). According to my research I don't believe we can prefix the base icon class, and we probably should not prefix the icon classes. If we are OK with this, let's close this issue or offer feedback.

**Comment by notmessenger** [comment]
@azizpunjani @juwara0 My only feedback, besides thanks for doing this research, is whether we want to specifically mention in the *README* file that icon classes are not prefixed and link to this issue explaining why.  Not saying we need to, just wondering if we think we need to.

**Comment by azizpunjani** [comment]
@notmessenger I would say we don't need to.
