### ISSUE TITLE
Fix sl-alert testing to test valid themes

### ISSUE THREAD

**Issue by erangeles** [softlayer/sl-ember-components#1468]
ember warning thrown in localhost/tests
`invalid theme ....`

culprit files
https://github.com/softlayer/sl-ember-components/blob/7e6c655b485cdcfbd92014d80654a455a2acd675/tests/integration/components/sl-alert-test.js#L36

https://github.com/softlayer/sl-ember-components/blob/7e6c655b485cdcfbd92014d80654a455a2acd675/tests/unit/components/sl-alert-test.js#L53

**Comment by erangeles** [comment]
@juwara0 taking this.

**Comment by juwara0** [comment]
The tests above are performing correctly. They were written to verify: https://github.com/softlayer/sl-ember-components/blob/7e6c655b485cdcfbd92014d80654a455a2acd675/addon/components/sl-alert.js#L112

**Comment by juwara0** [comment]
However, the titles of the tests and the messages in the asserts are not clear on what is being done. These could stand to be updated.
