### ISSUE TITLE
Test enum values in sl-alert component

### ISSUE THREAD

**Issue by erangeles** [softlayer/sl-ember-components#1470]
https://github.com/softlayer/sl-ember-components/blob/v0.11.0/tests/unit/components/sl-alert-test.js#L3

**Comment by erangeles** [comment]
@juwara0 taking this.

**Comment by azizpunjani** [comment]
@erangeles has this issue been resolved? Can it be closed?

**Comment by erangeles** [comment]
@azizpunjani https://github.com/softlayer/sl-ember-components/blob/v0.11.0/tests/unit/components/sl-alert-test.js#L48 . closing
