### ISSUE TITLE
allow sl-chart options to be set after render

### ISSUE THREAD

**Issue by alxyuu** [softlayer/sl-ember-components#1477]
There are cases when the highcharts options need to be updated after render, such as when the options depend on the data of the chart.

Specific use case: I'm using plotbands to show an uptime meter in the background while graphing data at the same time.

**Comment by notmessenger** [comment]
@alxyuu Please add this as a proposal to https://github.com/softlayer/sl-ember-components/issues/1254

**Comment by alxyuu** [comment]
@notmessenger is it not possible to work this myself? I already have the changes ready
