### ISSUE TITLE
CSS deprecation: 'webkitMovementX' is deprecated. Please use 'movementX' instead' in sl-chart component.

### ISSUE THREAD

**Issue by erangeles** [softlayer/sl-ember-components#1485]
steps to replicate:
- ember server in v0.11.0 branch
- visit `/#/demos/sl-chart` route
- click on a bar from the bar graph.
- open console, see deprecation

**Comment by notmessenger** [comment]
Have not looked at the code or the error but just thinking out loud...is this maybe because the version of highcharts we depend on is not version locked?
