### ISSUE TITLE
Keyboard shortcuts for sl-menu do not appear to be functioning correctly.

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1488]
http://localhost:4200/#/demos/sl-menu

@SpikedKira guessing this might be related to styling/DOM changes you made?

**Comment by SpikedKira** [comment]
https://github.com/softlayer/sl-ember-components/commit/3d1fb70aa53f02f117c0abe75a7601828347558d#diff-215a5a7e0a4c5390d9fae5fee0471a1b
