### ISSUE TITLE
Identify anywhere the {{each-in}} helper can be used in the current codebase

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1624]
http://emberjs.com/blog/2015/10/04/ember-2-1-released.html#toc_code-each-in-code-helper

**Comment by erangeles** [comment]
@notmessenger taking this.

**Comment by erangeles** [comment]
After diligent evaluation of the only iterative control structures in our component library[sources below), I have deemed it unnecessary to use the `each-in` helper as it does not provide value in our current or future implementations of our components.  

[sl-calender](https://github.com/softlayer/sl-ember-components/blob/v0.12.0/addon/templates/components/sl-calendar.hbs)

[sl-drop-button](https://github.com/softlayer/sl-ember-components/blob/v0.12.0/addon/templates/components/sl-drop-button.hbs)

[sl-grid](https://github.com/softlayer/sl-ember-components/blob/v0.12.0/addon/templates/components/sl-grid.hbs)

[sl-menu-item](https://github.com/softlayer/sl-ember-components/blob/v0.12.0/addon/templates/components/sl-menu-item.hbs)

[sl-menu](https://github.com/softlayer/sl-ember-components/blob/v0.12.0/addon/templates/components/sl-menu.hbs)

[sl-pagniation](https://github.com/softlayer/sl-ember-components/blob/v0.12.0/addon/templates/components/sl-pagination.hbs)
