### ISSUE TITLE
Identify all the places contextual components can be leveraged in the existing codebase

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1626]
http://emberjs.com/blog/2016/01/15/ember-2-3-released.html#toc_contextual-components

**Comment by erangeles** [comment]
@notmessenger taking this.

**Comment by erangeles** [comment]
resource note: https://ember-twiddle.com/4ae6c7817d92e2cb001d?openFiles=popover-container.template.hbs%2C

**Comment by erangeles** [comment]
resource note: https://kevink.me/2016/01/19/contextual-components-in-ember/
