### ISSUE TITLE
sl-grid documentation is out of date

### ISSUE THREAD

**Issue by arthur5005** [softlayer/sl-ember-components#1652]
Spent a bit of time working with sl-grid yesterday, then some time reviewing the code behind the components.

I believe the documentation is a bit out of date, here are a couple of things I found:

In the columns property definition there's a `template` attribute that I don't believe is being used and reference to a `rowController` I don't believe is being used either (or perhaps just not documented):
> template - The name of a template to use for the cell value, for more complex content; uses the rowController as its controller

The `sortColumn` property says the action has to accept two arguments, the column name and the column sort state, when really it's just 1: the column object itself
> The name of an action to trigger when a sortable column is selected for sorting. This action should accept two arguments: the column definition to sort on, and a boolean for whether the column is sorted ascending (true) or descending (false).

It would be really nice if the column definition did in-fact take a template. I know there's a discussion about revisiting the API for sl-grid #1261, personally I think this is pretty good so far, and it's still worth building on what's there. A powerful/flexible datagrid for ember would make a lot of people very happy.

**Comment by SpikedKira** [comment]
Thanks for the feedback!  I missed the documentation updates, we'll get to that soon.

**Comment by notmessenger** [comment]
Yes @arthur5005, thank you for pointing this out.  I have created https://github.com/softlayer/sl-ember-components/issues/1654 to update the documentation.

**Comment by notmessenger** [comment]
Closing this issue in favor of https://github.com/softlayer/sl-ember-components/issues/1652, which isolates the documentation changes from the `sl-grid` discussion.  Have made a comment on #1261 referring back this discussion as endorsement of the https://github.com/softlayer/sl-ember-components/issues/1261#issuecomment-190405887 proposal

**Comment by arthur5005** [comment]
Thanks guys!
