### ISSUE TITLE
Update grid documentation

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1654]
Extracted from https://github.com/softlayer/sl-ember-components/issues/1652

In the columns property definition there's a `template` attribute that I don't believe is being used and reference to a `rowController` I don't believe is being used either (or perhaps just not documented):
> template - The name of a template to use for the cell value, for more complex content; uses the rowController as its controller

The `sortColumn` property says the action has to accept two arguments, the column name and the column sort state, when really it's just 1: the column object itself
> The name of an action to trigger when a sortable column is selected for sorting. This action should accept two arguments: the column definition to sort on, and a boolean for whether the column is sorted ascending (true) or descending (false).

**Comment by erangeles** [comment]
taking this.
