### ISSUE TITLE
Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#1681]
When using `ember` version `2.11.0+` (`ember-cli` version `2.11.0`)

**Comment by notmessenger** [comment]
Upgrading `bootstrap` to `3.3.7` resolves this issue.

Need to update the dependency version in the blueprint - https://github.com/softlayer/sl-ember-components/blob/master/blueprints/sl-ember-components/index.js#L6

**Comment by tinyweasel** [comment]
I'm getting Uncaught Error: Could not find module `ember-resolver` imported from `npm-test/resolver` but my Bootstrap is 3.3.7. Any ideas?

**Comment by notmessenger** [comment]
@tinyweasel Is the version only changed in your _bower.json_ file or have you done a `bower install` as well?

Whenever I run into these types of errors the first thing I do is run `npm set progress=false && rm -rf node_modules && rm -rf bower_components && npm cache clean && bower cache clean && npm install && bower install` as it will often clear such things up.  If this problem still exists after this then we will have to dig into it further.

**Comment by tinyweasel** [comment]
I'd done all of that except `npm set progress=false`. I'm trying it again, I'll let you know if the problem persists.
