### ISSUE TITLE
Include ember-cli-es5-shim only in test environment

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#187]
https://github.com/ember-cli/ember-cli/issues/2634

**Comment by notmessenger** [comment]
@joshforisha I'd like to get your opinion on this:

If the only place we were using .bind() calls (the current offenders - there can be others) was in the dummy app then we could very easily only include ember-cli-es5-shim (specifically, its related bower file) in the test environment, which is the focus of this issue.  However, we are also using it in these locations:

https://github.com/softlayer/sl-ember-components/blob/7ea30420ec7fcbfabcd43e366630ac23d1abb0f9/addon/components/sl-menu.js#L497

https://github.com/softlayer/sl-ember-components/blob/7ea30420ec7fcbfabcd43e366630ac23d1abb0f9/addon/components/sl-radio-group.js#L124

https://github.com/softlayer/sl-ember-components/blob/c49dcb79216f2f66b10c7985df6e11b11f2fe080/addon/components/sl-button.js#L163

https://github.com/softlayer/sl-ember-components/blob/c49dcb79216f2f66b10c7985df6e11b11f2fe080/addon/components/sl-button.js#L177

https://github.com/softlayer/sl-ember-components/blob/7ea30420ec7fcbfabcd43e366630ac23d1abb0f9/addon/mixins/sl-modal.js#L109-113

So the question that leaves us with is whether we want to use .bind() calls in our add on code or use Ember.run.bind() instead.  bind() compatibility can be viewed at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Browser_compatibility, with IE9 being the deciding factor.  While SoftLayer only needs to support current browser version and the one previous, is IE9 too high of a version to provide the feature sets to users of this repository we want to?

**Comment by joshforisha** [comment]
I'm not concerned with supporting anything other than what SoftLayer does.

**Comment by notmessenger** [comment]
As a side-effect of https://github.com/softlayer/sl-ember-components/pull/257 the occurrences of .bind() have been removed from `Haddon/components/sl-button` and `addon/mixins/sl-modal.js`.

Still need to remove in `addon/components/sl-menu` and `addon/components/sl-radio-group`.  Besides being the correct thing to do this replacement will also head off failures we will encounter when creating the tests for these components.

**Comment by notmessenger** [comment]
https://github.com/softlayer/sl-ember-components/issues/258 and https://github.com/softlayer/sl-ember-components/issues/259 have been created to track these

**Comment by notmessenger** [comment]
During the research of this task and due to the completion of the other referenced issues, it has been determined that the ember-cli-es5-shim is actually not needed.  This issue is being closed in favor of  https://github.com/softlayer/sl-ember-components/issues/265
