### ISSUE TITLE
Determine whether styles can be moved from /app to /addon folder

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#190]
This comment and the one below it: https://github.com/ember-cli/ember-cli/issues/3073#issuecomment-71324258

**Comment by notmessenger** [comment]
On the same topic, but older https://github.com/ember-cli/ember-cli/issues/1853

**Comment by azizpunjani** [comment]
This will work with regular .css files but doesn't seem to work with .less files. Maybe there is another way to accomplish this.

**Comment by azizpunjani** [comment]
This user rwwagner90 in this thread is experiencing the same issue I am talking about https://github.com/ember-cli/ember-cli/issues/3490.
