### ISSUE TITLE
Add tests for sl-select component

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#230]

**Comment by notmessenger** [comment]
https://github.com/softlayer/sl-ember-components/issues/250 may possibly become resolved as well as code is potentially refactored to aid in testing

**Comment by alxyuu** [comment]
@notmessenger taking over this issue from @azizpunjani

**Comment by alxyuu** [comment]
disableSearch only applies to single item select boxes per http://select2.github.io/select2/#documentation

Documentation will be updated to reflect this.

**Comment by notmessenger** [comment]
As https://github.com/softlayer/sl-ember-components/issues/16 has not been resolved yet approach the test against the current functionality which is that both the `required` and `optional` properties are treated independently of each other, like is how similarly approached in the sl-textarea, sl-radio-group, and sl-input components

**Comment by notmessenger** [comment]
Replaced by https://github.com/softlayer/sl-ember-components/issues/456
