### ISSUE TITLE
Add tests for sl-modal mixin

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#242]

**Comment by erangeles** [comment]
@notmessenger taking this one.

**Comment by notmessenger** [comment]
@erangeles Check with @azizpunjani as this is either likely no longer needed or something that will be addressed by his https://github.com/softlayer/sl-ember-components/pull/380

**Comment by azizpunjani** [comment]
@erangeles sl-modal-mixin will be going away because we have a sl-modal-service in PR #380.

**Comment by erangeles** [comment]
@azizpunjani got it. Thanks for the heads up, no longer taking ownership of that issue then.
