### ISSUE TITLE
Add test for sl-notify-view mixin

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#243]
Is related to https://github.com/softlayer/sl-ember-components/issues/24

**Comment by erangeles** [comment]
@notmessenger taking this one.

**Comment by notmessenger** [comment]
@erangeles Have you determined the answer https://github.com/softlayer/sl-ember-components/issues/24?

**Comment by notmessenger** [comment]
See https://github.com/softlayer/sl-ember-components/issues/24
