### ISSUE TITLE
Address complex method initSelection() in addon/components/sl-select.js

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#250]
https://codeclimate.com/github/softlayer/sl-ember-components/issues/categories/complexity

**Comment by alxyuu** [comment]
@notmessenger This issue no longer shows up on code climate. However, it doesn't look like there have been any major changes to the function, other than converting to fat arrow function notation. Could it be that code climate doesn't recognize these functions properly?

**Comment by notmessenger** [comment]
Replaced by https://github.com/softlayer/sl-ember-components/issues/456
