### ISSUE TITLE
Move test helper "ajax helper" to sl-ember-test-helpers repository

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#256]

**Comment by notmessenger** [comment]
https://github.com/softlayer/sl-ember-test-helpers/pull/54 added the `ajax` helper to sl-ember-test-helpers

**Comment by joshforisha** [comment]
The AjaxHelper has been removed from sl-ember-components as of #271.

**Comment by notmessenger** [comment]
https://github.com/softlayer/sl-ember-components/pull/271 removed the ajax helper from this repository
