### ISSUE TITLE
Questions about isLowPercentage() in sl-progress-bar

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#301]
* Description of method says "Whether the progress value is below a certain level"
** Should the comparison level be user-providable?  If not, this description should be changed.

* Why is less than 50 the threshold for isLowPercentage?  Goes back to question above about whether this should be user supplied.
** Why is there not a isHighPercentage?

**Comment by joshforisha** [comment]
Using isLowPercentage is mostly done for styling. A class is added below value 50 so that the label text is moved to the right of the progress for readability. Having an isHighPercentage wouldn't be useful in the same way.
