### ISSUE TITLE
sl-date-range-picker

### ISSUE THREAD

**Issue by Samsinite** [softlayer/sl-ember-components#305]
Your picker is throwing an exception because it sets the date picker change handlers to `startDateChange` and `endDateChange` actions that not defined on the sl-date-range-picker itself. I'm guessing that this component hasn't been used recently? :)

```
Uncaught Error: <items@component:sl-date-range-picker::ember1453> had no action handler for: startDateChange
```

**Comment by Samsinite** [comment]
For anyone using ember-cli running into this issue, just create the correct template
`app/templates/components/sl-date-range-picker.hbs` file to override the existing one:
```html
{{#if label}}
    <label {{bind-attr for=inputElementId}}>{{label}}</label>
{{/if}}

<div class="row">
    {{sl-date-picker
        class="sl-daterange-start-date col-md-6"
        endDate=latestStartDate
        placeholder=startDatePlaceholder
        startDate=minDate
        value=startDateValue
        inputElementIdBinding="inputElementId"
    }}

    {{sl-date-picker
        class="sl-daterange-end-date col-md-6"
        endDate=maxDate
        placeholder=endDatePlaceholder
        startDate=earliestEndDate
        value=endDateValue
    }}
</div>

{{#if helpText}}
    <p class="help-block">{{helpText}}</p>
{{/if}}
```

**Comment by joshforisha** [comment]
It's odd that I'm not seeing any errors at all from this... I went ahead and removed the change bindings, as they're clearly not needed anyway.
