### ISSUE TITLE
Tab Panes that Use Templates gives error: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by jdhines** [softlayer/sl-ember-components#308]
I had ember-for-bootstrap tabs working, but wanted to switch to SL components because it seems like it's being kept more up to date.

In any case, I got progress bars working, as well as tabs, but only with static content within the tab panes. If I try to set `templateName` then I get this error. I tried both with the templates I actually need, as well as simply-named, top-level ones, but it gave the same error.

*Simple templates*
````
{{#sl-tab-panel}}
  {{sl-tab-pane label="Project" name="project" templateName="about"}}

  {{sl-tab-pane label="Team" name="team" templateName="help"}}

{{/sl-tab-panel}}
````
*Templates in a folder, with a dash in the name (these are the ones I would actually use)*
````
  {{sl-tab-pane label="Project" name="project" templateName="budget/project-budget"}}

  {{sl-tab-pane label="Team" name="team" templateName="budget/resource-budget"}}
````
![image](https://cloud.githubusercontent.com/assets/2855641/6676039/484b4c7c-cbfb-11e4-9418-02a63f52c892.png)

**Comment by jdhines** [comment]
I'm on Ember 1.10, which doesn't use Handlebars, but I see that the getKey helper uses Ember.Handlebars.makeBoundHelper. Is this the cause of the error I'm seeing? Is sl-components incompatible with Ember 1.10?

**Comment by notmessenger** [comment]
They may be.  We are planning an upgrade to Ember 1.10 in the very near future so will be taking a look at this soon.

**Comment by kaosko** [comment]
I see the same problem with the latest I pulled down just today. The issue seems to be that options.contexts is null at line 6 of render-tab-pane.js (var templateName = options.contexts[ 0 ][ templateKey ];). Inline content works fine, don't quite understand yet where that context is (not) set.

**Comment by kaosko** [comment]
Verified that fix to https://github.com/joshforisha/sl-ember-components/blob/ember-cli/0-2-3/addon/helpers/render-tab-pane.js works.

**Comment by notmessenger** [comment]
Closed by https://github.com/softlayer/sl-ember-components/pull/344

**Comment by jdhines** [comment]
Sorry, I know this is way old, but how was this fixed by 344? I don't see that a `templateName` property is available.

**Comment by notmessenger** [comment]
I have given this a once-over and the answer is not immediately clear.  It will require more research to make a determination.
