### ISSUE TITLE
Modify Brocfile.js

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#346]
Replace assignment of isProduction with 'production' === EmberApp.env() or probably even better replace the check for it with app.env !== 'production'

**Comment by erangeles** [comment]
@notmessenger picking this up.

**Comment by notmessenger** [comment]
https://github.com/softlayer/sl-ember-components/pull/463 likely resolved this?

**Comment by erangeles** [comment]
@notmessenger yes it did. Should have closed it with my commit message as well but wanted to get you to inspect it first.
