### ISSUE TITLE
Remove alias to _parentView._controller

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#350]
https://github.com/softlayer/sl-ember-components/blob/99ad0a462d8cf0e676c87adec458a1fe48de74e7/addon/components/sl-grid.js#L346

http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html#toc_notable-breaking-changes-in-ember-2-0 states:

```{{each item itemController="some-controller"}}``` - This usage can be replaced by nesting a component inside the item, and by using helpers.

The last section of http://emberjs.com/deprecations/v1.x/#toc_migrating-away-from-the-view-helper states:

"Note that a component is always its own context in a template. A view's template may have had access to other variables that were present where it was called, such as a controller. A component template will always be isolated, and if data is needed it should be passed upon invocation. For example:"

```
{{show-menu options=controller.menuOptions}}
```

**Comment by notmessenger** [comment]
Either as part of this issue, or in a new one if more appropriate, also consider yielded context in components for the rendering of the rows.  This may address this scenario.

**Comment by erangeles** [comment]
@notmessenger taking this.

**Comment by notmessenger** [comment]
Postponing until after the https://github.com/softlayer/sl-ember-components/milestones/v0.10.0%20(Ember%20Upgrade) Milestone

**Comment by erangeles** [comment]
source: http://emberjs.com/blog/2015/05/05/glimmer-merging.html

"Glimmer, through HTMLBars, has a much clearer concept of "scope", and features like {{yield}} work directly with that scope object. We were able to get the Ember test suite passing by implementing the old semantics on top of the new scope concept, but we are aware that we have gaps in our implementation."

**Comment by notmessenger** [comment]
May be of use - http://burstcreations.com/blog/data-down-actions-up/
