### ISSUE TITLE
addon/templates/components/sl-chart.hbs is binding unescaped style attributes

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#353]
WARNING: Binding style attributes may introduce cross-site scripting vulnerabilities; please ensure that values being bound are properly escaped. For more information, including how to disable this warning, see http://emberjs.com/deprecations/v1.x/#toc_binding-style-attributes.

http://emberjs.com/deprecations/v1.x/#toc_binding-style-attributes

<div style={{style}} class="chart sl-maskable-content"></div>

**Comment by azizpunjani** [comment]
This should not be an issue as we do return a `SafeString` https://github.com/softlayer/sl-ember-components/blob/develop/addon/components/sl-chart.js#L194

**Comment by notmessenger** [comment]
Is there something about our syntax that isn't quite right that is causing the warnings to display?  The docs say that once it is done correctly the warnings should go away.

**Comment by azizpunjani** [comment]
Hmm, I'm not seeing any warnings for sl-chart. Are you still getting warnings? If so, when? When running tests?

**Comment by notmessenger** [comment]
Per our in-person conversation I am now squared away on my understanding and am closing this issue.
