### ISSUE TITLE
Refactor sl-menu

### ISSUE THREAD

**Issue by joshforisha** [softlayer/sl-ember-components#359]
The menu is view based and inefficiently recursive. It should be updated to have at least one sub-component and support component-based usage within an application.

**Comment by notmessenger** [comment]
Related to:
* https://github.com/softlayer/sl-ember-components/issues/347
* https://github.com/softlayer/sl-ember-components/issues/249
* https://github.com/softlayer/sl-ember-components/issues/248
* https://github.com/softlayer/sl-ember-components/issues/28

**Comment by notmessenger** [comment]
Resolved by https://github.com/softlayer/sl-ember-components/pull/499
