### ISSUE TITLE
Ember.EnumberableUtils.map is deprecated, please refactor to use Array.prototype.map

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#367]
These may be affected:

* https://github.com/softlayer/sl-ember-components/blob/c2d14ee32fc9089a7d24e89d382bead380309cf3/addon/components/sl-grid-cell.js#L111
* https://github.com/softlayer/sl-ember-components/blob/9962cea468f9cb055422c6e679509864af0067b5/addon/components/sl-alert.js#L111
* https://github.com/softlayer/sl-ember-components/blob/9962cea468f9cb055422c6e679509864af0067b5/addon/components/sl-button.js#L190
* https://github.com/softlayer/sl-ember-components/blob/9962cea468f9cb055422c6e679509864af0067b5/addon/components/sl-button.js#L227
* https://github.com/softlayer/sl-ember-components/blob/9962cea468f9cb055422c6e679509864af0067b5/addon/components/sl-drop-button.js#L150
* https://github.com/softlayer/sl-ember-components/blob/9962cea468f9cb055422c6e679509864af0067b5/addon/components/sl-progress-bar.js#L138
* https://github.com/softlayer/sl-ember-components/blob/0ce928e1f811edb0bf859b44759cca212aeabe7f/addon/components/sl-tab-panel.js#L231

Once Ember 1.13 is used by this addon

**Comment by juwara0** [comment]
This issue can be closed. I checked each of the links above and they have already been refactored to not use Object.keys().map(). I also did a grep on the repo looking for Ember.EnumberableUtils.map,  EnumberableUtils.map or Object.keys().map but did not find any outstanding instances
