### ISSUE TITLE
Ember.EnumberableUtils.filter is deprecated, please refactor to use Array.prototype.filter

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#369]
May be affected:

* https://github.com/softlayer/sl-ember-components/blob/0ce928e1f811edb0bf859b44759cca212aeabe7f/addon/components/sl-input.js#L140

Once Ember 1.13 is used by this addon

**Comment by juwara0** [comment]
This issue can be marked as resolved. My investigation into this concludes that this is not an issue. Looking through our code and the Ember API for this method does not indicate that we need to refactor anything. Additionally, I am not seeing the deprecation warnings listed above when running the tests or demo app for sl-input.
