### ISSUE TITLE
Ember.EnumberableUtils.indexOf is deprecated, please refactor to use Array.prototype.indexOf

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#370]
May be affected:

* https://github.com/softlayer/sl-ember-components/blob/c2d14ee32fc9089a7d24e89d382bead380309cf3/addon/components/sl-grid-cell.js#L111
* https://github.com/softlayer/sl-ember-components/blob/c2d14ee32fc9089a7d24e89d382bead380309cf3/addon/components/sl-grid-cell.js#L153
* https://github.com/softlayer/sl-ember-components/blob/9962cea468f9cb055422c6e679509864af0067b5/addon/components/sl-alert.js#L111
* https://github.com/softlayer/sl-ember-components/blob/9962cea468f9cb055422c6e679509864af0067b5/tests/unit/components/sl-menu-test.js#L63
* https://github.com/softlayer/sl-ember-components/blob/9962cea468f9cb055422c6e679509864af0067b5/addon/components/sl-button.js#L227
* https://github.com/softlayer/sl-ember-components/blob/9962cea468f9cb055422c6e679509864af0067b5/addon/components/sl-drop-button.js#L150
* https://github.com/softlayer/sl-ember-components/blob/9962cea468f9cb055422c6e679509864af0067b5/addon/components/sl-progress-bar.js#L138
* https://github.com/softlayer/sl-ember-components/blob/0ce928e1f811edb0bf859b44759cca212aeabe7f/addon/components/sl-select.js#L196
* https://github.com/softlayer/sl-ember-components/blob/0ce928e1f811edb0bf859b44759cca212aeabe7f/addon/components/sl-tab-panel.js#L231

Once Ember 1.13 is being used by this library

**Comment by juwara0** [comment]
I am working this issue.

**Comment by juwara0** [comment]
This issue can be marked as resolved. My investigation into this concludes that this is not an issue. Looking through our code and the Ember API for this method does not indicate that we need to refactor anything. Additionally, I am not seeing the deprecation warnings listed above when running the tests or demo app for the components listed above.
