### ISSUE TITLE
Ember.EnumerableUtils.removeObject is deprecated

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#371]
https://github.com/softlayer/sl-ember-components/blob/0ce928e1f811edb0bf859b44759cca212aeabe7f/addon/components/sl-menu.js#L641

Once Ember 1.13 is being used by this addon

**Comment by jonathandavidson** [comment]
Working on this.

**Comment by jonathandavidson** [comment]
This issue can be closed. `removeObject()` is no longer used anywhere in this repo.
