### ISSUE TITLE
Dropdown options are shifted off of the dropdown list element.

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#389]
Users @huskerdu and @jkgisme on Slack have reported that the dropdown options are shifted off of the dropdown list element. @huskerdu provided these screen shots: http://cl.ly/image/0Q1j3U0w2t1p and http://cl.ly/image/0C1Q3P2l2D2v.  @jkgisme is using Chrome on OS X and reports that it happens because the page's vertical scroll bar disappears when the dropdown list appears so all the content on the page except the dropdown list moves to the right half a centimeter.  They added `html { overflow-y: scroll; }` to the app.less and it seems to have fixed it.

**Comment by erangeles** [comment]
@notmessenger picking this up
