### ISSUE TITLE
Ember.typeOf( Symbol ) returns "function", which will cause problems in this code

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#396]
https://github.com/softlayer/sl-ember-components/blob/0ce928e1f811edb0bf859b44759cca212aeabe7f/addon/components/sl-select.js#L132

https://github.com/softlayer/sl-ember-components/blob/0ce928e1f811edb0bf859b44759cca212aeabe7f/addon/components/sl-select.js#L159

https://github.com/softlayer/sl-ember-components/blob/e09c1503af73e9c610c997ead73c093574303ee0/addon/components/sl-input.js#L130

https://github.com/softlayer/sl-ember-components/blob/e09c1503af73e9c610c997ead73c093574303ee0/addon/components/sl-input.js#L143

https://github.com/emberjs/ember.js/issues/11673 has been opened regarding this issue in Ember.js so depending on the timing of when the issue is worked on it might already be resolved or we will need to accommodate it via a workaround in our code via using `typeof`.  If we do the latter then we need to create an issue to remove our workaround once https://github.com/emberjs/ember.js/issues/11673 is resolved and released.

**Comment by notmessenger** [comment]
https://github.com/emberjs/ember.js/issues/11673 is not going to be resolved at this time so calls to `Ember.typeOf()` that are compared to `'object'` must also contain logic similar to `&& 'symbol' != typeof`

**Comment by alxyuu** [comment]
@notmessenger why are people passing in the Symbol function directly? If anything, users should be passing in something like Symbol( 'foo' ), for which Ember.typeOf does return object.

**Comment by notmessenger** [comment]
It is correct that Ember.typeOf() will return an object type, but a symbol is a symbol, not an object - https://hacks.mozilla.org/2015/06/es6-in-depth-symbols/.  As such the bug discussed in emberjs/ember.js#11673 comes into play.

**Comment by azizpunjani** [comment]
Going to be working on this one.

**Comment by notmessenger** [comment]
https://github.com/softlayer/sl-ember-components/issues/456 and https://github.com/softlayer/sl-ember-components/issues/457 render this issue irrelevant.
