### ISSUE TITLE
Implement skipped tests

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#398]

**Comment by notmessenger** [comment]
Blocked until v0.10.0 release

**Comment by notmessenger** [comment]
Assigning this to you @azizpunjani as it fits right in with https://github.com/softlayer/sl-ember-components/issues/588 and you may actually have even already addressed this.

**Comment by azizpunjani** [comment]
@notmessenger please close as sl grid tests branch has been merged.
