### ISSUE TITLE
sl-select doesn't show pre-existing selection?

### ISSUE THREAD

**Issue by JKGisMe** [softlayer/sl-ember-components#410]
I have tried to figure this out for a bit but I can't seem to get it. I'm creating a form that is designed to be used to create new data or edit pre-existing data. When there is pre-existing data already set, the sl-select ui seems to be unaware of it. 

Take, for example, the numbers example in the demo. If you try to set `selectedNums=[40, 50]` in your controller and `value=selectedNums` in the hbs for the sl-select's properties it will still render as though there are no selected numbers.  

I'm thinking that when the select initializes it needs to be given the value.

**Comment by alxyuu** [comment]
@notmessenger picking this up.
@JKGisMe Currently, sl-select does not support passing arrays for value. However, you can set `value="40,50"` and it will split on commas. I will add support for arrays in this fix.
