### ISSUE TITLE
Test needs to contain assertion for null

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#413]
https://github.com/softlayer/sl-ember-components/blob/d1cb16dc178d9406339e046e5cf87a6545c66757/tests/unit/components/sl-tooltip-test.js#L38

https://github.com/softlayer/sl-ember-components/blob/d1cb16dc178d9406339e046e5cf87a6545c66757/tests/unit/components/sl-tooltip-test.js#L175

**Comment by erangeles** [comment]
picking this up, as it is related to #397
