### ISSUE TITLE
Add test to sl-date-range-picker for helpText

### ISSUE THREAD

**Issue by alxyuu** [softlayer/sl-ember-components#423]
There should be a test that verifies that helpText is undefined by default and that no dom element is created, as well as verify the correct element is created when helpText is set

**Comment by notmessenger** [comment]
https://github.com/softlayer/sl-ember-components/pull/412 will address the test about the correct element being created, so this issue only needs to test that `helpText` is passed along.

**Comment by alxyuu** [comment]
Actually, helpText isn't being passed along, it's an element in the date range picker. I missed testing for it in #210

**Comment by notmessenger** [comment]
Replaced by https://github.com/softlayer/sl-ember-components/issues/455
