### ISSUE TITLE
Date picker stays open during running of tests at /tests

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#424]
https://goo.gl/4vDLgq

Most likely introduced in https://github.com/softlayer/sl-ember-components/pull/402 but not certain nor specifically matters

**Comment by alxyuu** [comment]
It's from the focus test which causes the end date picker to open. Is this even be an issue...?

**Comment by notmessenger** [comment]
Yes.  Tests should be atomic and not leave any artifacts for other ones.  While it may not cause problems for other tests within the same suite, it can certainly cause problems for other test modules, and even more so once functional tests get ran as well.  It is not reasonable to expect every test to have to reset the app to a visual state it has no knowledge of but it is reasonable to expect a test to clean up after itself.
