### ISSUE TITLE
Evaluate the use of changeDate in sl-date-picker and sl-date-range-picker

### ISSUE THREAD

**Issue by alxyuu** [softlayer/sl-ember-components#448]
Currently, both sl-date-picker and sl-date-range-picker place changeDate listeners on the start date input dom element. However, the listener from sl-date-picker does not seem to serve any purpose. Evaluate if the listener should be removed from sl-date-picker or if the listener should be removed from sl-date-range-picker and action bubbling should be used.

**Comment by notmessenger** [comment]
Replaced by https://github.com/softlayer/sl-ember-components/issues/454

**Comment by notmessenger** [comment]
Replaced by https://github.com/softlayer/sl-ember-components/issues/455
