### ISSUE TITLE
Refactor test(s) that check for parameter types

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#467]
* Align with the pattern in https://github.com/softlayer/sl-ember-components/blob/develop/tests/unit/components/sl-chart-test.js#L99
* Do not include test for `Symbol`

**Comment by azizpunjani** [comment]
Starting work on this. @notmessenger please assign this task to me.

**Comment by notmessenger** [comment]
https://github.com/softlayer/sl-ember-components/issues/479 will be modifying the sample to follow

**Comment by azizpunjani** [comment]
@notmessenger can this be closed?

**Comment by notmessenger** [comment]
Only if there are no files needing this change.  #479 only updated the sample to follow in the sl-chart-test file - not address any of the reasons for this issue existing.

**Comment by azizpunjani** [comment]
@notmessenger verified no other files need these changes. All files have been refactored to use the new pattern.
