### ISSUE TITLE
Refactor test to use assert.throws() call

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#468]
https://github.com/softlayer/sl-ember-components/blob/3e6b4f324ed0586654ad9f7f318647500310bf9d/tests/unit/services/sl-modal-test.js#L49

https://github.com/softlayer/sl-ember-components/blob/develop/tests/unit/components/sl-chart-test.js#L99 is an example usage of this method.

**Comment by azizpunjani** [comment]
Starting work on this. @notmessenger please assign to me.
