### ISSUE TITLE
Document how consuming application should reference .LESS files

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#47]
@import 'sl-ember-components';

**Comment by zcourts** [comment]
What's the recommended approach for doing this when your application uses sass instead of less?
For now, I've just built the CSS, put it into sl.scss and imported it.

**Comment by notmessenger** [comment]
https://github.com/ember-cli/ember-cli/pull/1918 may be (part of) the answer

**Comment by notmessenger** [comment]
https://github.com/ember-cli/ember-cli/issues/3490

**Comment by notmessenger** [comment]
All of the issues being worked in the `v0.11.0` milestone are to address the issue of styling and playing much nicer with consuming applications.  Specific to this issue, and supported by work in other issues, https://github.com/softlayer/sl-ember-components/commit/ace6e5eef7794d5a2bb32ca058c2da7acd280f82 is the answer to this issue's question.
