### ISSUE TITLE
sl-input typeahead no longer works

### ISSUE THREAD

**Issue by alxyuu** [softlayer/sl-ember-components#477]
typeahead no longer works on the current develop branch

**Comment by notmessenger** [comment]
https://github.com/softlayer/sl-ember-components/pull/451 may resolve this

**Comment by azizpunjani** [comment]
Yes https://github.com/softlayer/sl-ember-components/pull/451 should resolve this issue.

**Comment by notmessenger** [comment]
Resolved by https://github.com/softlayer/sl-ember-components/pull/451
