### ISSUE TITLE
callSubject should be called as a function

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#479]
https://github.com/softlayer/sl-ember-components/blob/4c911a21aed868253c5fb8dee2eb1ebf6a3e2dc9/tests/unit/components/sl-chart-test.js#L167

https://github.com/softlayer/sl-ember-components/blob/4c911a21aed868253c5fb8dee2eb1ebf6a3e2dc9/tests/unit/components/sl-chart-test.js#L240

**Comment by azizpunjani** [comment]
Will be fixed by https://github.com/softlayer/sl-ember-components/pull/487
