### ISSUE TITLE
DEPRECATION: Using `{{view}}` or any path based on it ('modules/sl-ember-components/templates/components/sl-drop-button.hbs' @ L7:C4) has been deprecated. [deprecation id: view.keyword.view] 

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#549]
See http://emberjs.com/deprecations/v1.x#toc_view-and-controller-template-keywords for more details.

**Comment by notmessenger** [comment]
Also DEPRECATION: Using `{{view}}` or any path based on it ('modules/sl-ember-components/templates/components/sl-drop-button.hbs' @ L8:C8) has been deprecated.

**Comment by notmessenger** [comment]
Encountered during `ember test`

**Comment by juwara0** [comment]
I am taking a look at this issue.
