### ISSUE TITLE
"DEPRECATION: You modified sl-select-view.elementId twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 2.0

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#568]

**Comment by notmessenger** [comment]
May possibly be of assistance - https://github.com/emberjs/ember.js/issues/11156

**Comment by azizpunjani** [comment]
Fixed by https://github.com/softlayer/sl-ember-components/pull/662

**Comment by azizpunjani** [comment]
@notmessenger this should be resolved by https://github.com/softlayer/sl-ember-components/pull/662, please close.
