### ISSUE TITLE
"DEPRECATION: You modified (no label) twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 2.0

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#573]

**Comment by notmessenger** [comment]
May possibly be of assistance - https://github.com/emberjs/ember.js/issues/11156

**Comment by ksnyde** [comment]
I'm having the same issue

**Comment by azizpunjani** [comment]
@notmessenger resolved by https://github.com/softlayer/sl-ember-components/pull/798
