### ISSUE TITLE
"DEPRECATION: You modified view.href twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 2.0

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#574]

**Comment by notmessenger** [comment]
May possibly be of assistance - https://github.com/emberjs/ember.js/issues/11156

**Comment by juwara0** [comment]
This issue can be closed. I am not seeing any deprecation messages related to sl-textarea. My thought is that it was probably fixed when Aziz updated the sl-input-based mixin which is used by sl-textarea.
