### ISSUE TITLE
for attribute in label does not correctly set focus on element

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#61]
The label never focuses the select element, as the element is processed by the Select2 plugin and given a slightly modified ID.

**Comment by alxyuu** [comment]
@notmessenger picking this one up

**Comment by notmessenger** [comment]
There is an `input` element with the classes of `select2-focusser select2-offscreen` applied to it.  This element's id should be used for the label's `for` value.  This will mimic the focusing of the element when the label is clicked just like normal label for usage.  Do not open the control upon selection.

**Comment by alxyuu** [comment]
@notmessenger that is applicable for single select boxes, but not multiple. Multiple select boxes have a input with `select2-input`, but setting label for to this causes the selection to open when the label is clicked. I think if one type of select is going to open both should for consistency.

**Comment by notmessenger** [comment]
@joshforisha Want to lend your opinion?  Still tying into the click event which we're not liking so need to decide if multiple options auto-open, which might be the acceptable compromise here.  Using the label for focus is discussed in the Select2 repo at https://github.com/select2/select2/issues/2311

**Comment by alxyuu** [comment]
Sorry, should have clarified: the select2 focus event only gives focus, it doesn't open the selection. However, using for does open the selection on multiple select boxes.

**Comment by notmessenger** [comment]
Replaced by https://github.com/softlayer/sl-ember-components/issues/456
