### ISSUE TITLE
Ensure that jQuery version bump has not caused any issues with the components that have dependencies that include jQuery

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#616]
https://github.com/softlayer/sl-ember-components/commit/62a666635956d914ba4c7cb6338f0b3cfa98814d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 introduced the change

This should be addressed as one of the last issues in the https://github.com/softlayer/sl-ember-components/milestones/v0.10.0%20(Ember%20Upgrade) milestone so that all of the deprecations and tests have been addressed.

**Comment by SpikedKira** [comment]
1.11.3 = 2015-04-28T16:19Z
1.11.2 = 2014-12-17T15:27Z

changes:
 a) how length is checked of "array-like" entities

effects:
 a) .each() and .map() check if the operand is an array using an internal function, which in turn checks for a length.
       previously, this was 'obj.length' now it is '"length" in obj && obj.length'

**Comment by SpikedKira** [comment]
1.11.1 = 2014-05-01T17:42Z

changes:
 a) sizzle version bump ( v1.10.19 -> v.2.2.0-pre )
 b) internal code rearrangement
 c) rounding fix

effects:
 a) unknown (several code-speed updates; fix for iframe document model; some changes for IE<9)
 b) none
 c) none
