### ISSUE TITLE
Components that mix in sl-input-based are disabled

### ISSUE THREAD

**Issue by azizpunjani** [softlayer/sl-ember-components#657]
`sl-input`, `sl-select` and `sl-text-area` all show up as disabled after the upgrade. Ember interprets `readonly: false` as readonly="false" instead of leaving off the `readonly` attribute. This is causing all inputs, select and text areas ( components that mix in sl-input-based ) to show up as readonly. The same is happening for the `disabled` attribute.

**Comment by azizpunjani** [comment]
Examples of issue.

![image](https://cloud.githubusercontent.com/assets/156746/9253655/a46445d0-41a4-11e5-865c-3b73c9099916.png)

![image](https://cloud.githubusercontent.com/assets/156746/9253676/bd0226fc-41a4-11e5-9463-ca7a67cc0d39.png)

![image](https://cloud.githubusercontent.com/assets/156746/9253728/08a1eb42-41a5-11e5-89fc-3990f9834f0b.png)

**Comment by notmessenger** [comment]
Resolved by https://github.com/softlayer/sl-ember-components/pull/658
