### ISSUE TITLE
Adding bootstrap.js import to ember-cli-build.js breaks sl-drop-button

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#663]
Since both bootstrap and sl-bootstrap are registering toggle listeners.  Figure out approach and update README.md as well as create any appropriate issues to address the problem.

**Comment by SpikedKira** [comment]
We should discuss this.  From the looks of things, we rolled our own custom version of bootstrap.  If that's the case we should never include the real one.  Maybe I have misinterpreted the meaning of this issue?
