### ISSUE TITLE
Refactor the format of the template rendering in the tests to pass linting checks

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#682]
The changes in https://github.com/softlayer/sl-ember-components/pull/647 introduced this problem.

https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/integration/components/sl-modal-body-test.js#L12 should be brought inline as well

**Comment by theoshu** [comment]
all the sl-modal*-tests pass. Is there something I'm missing?

**Comment by notmessenger** [comment]
@juwara0 and @azizpunjani - let's discuss this tomorrow and determine how to proceed

**Comment by notmessenger** [comment]
@theoshu The changes from https://github.com/softlayer/sl-ember-components/pull/647 appear to have already been resolved, but verify this.

This still needs to be addressed:  https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/integration/components/sl-modal-body-test.js#L12 should be brought inline as well

**Comment by theoshu** [comment]
Looks good, this can be closed.
