### ISSUE TITLE
DOM structure is not accurate

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#686]
Usage such as `{{sl-radio disabled=true label="Disabled radio button"}}` generates the following HTML:

```
<div id="ember691" class="ember-view sl-radio disabled radio" disabled="true">
    <label for="ember712">
        <input id="ember712" class="ember-view ember-text-field" disabled type="radio" value=""> Disabled radio button
    </label>
</div>
```

`disabled="true"` should not be applied to the containing div.

**Comment by Yogeswar** [comment]
This is not reproducible.

generated HTML:
<div id="ember741" class="ember-view sl-radio disabled radio"><label>
    <input id="ember742" disabled="" type="radio" class="ember-view ember-text-field">
    Disabled radio button
</label>
</div>
