### ISSUE TITLE
What are we intending with the use of the readonly attribute?

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#689]
According to http://www.w3.org/TR/html-markup/input.radio.html the `readonly` attribute is not valid on `input type=radio`.  Even if it was valid, `readonly` represents a control whose value is not meant to be edited.  (http://www.w3.org/TR/html-markup/input.text.html#input.text.attrs.readonly)

**Comment by SpikedKira** [comment]
The above link to w3.org states "attribute boolean readOnly;" note the capital 'O'.  It is a valid property.
