### ISSUE TITLE
Refactor setting of property

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#735]
tests/integration/components/sl-modal-test.js

Change `this.set( 'isOpen', 'initial Value' );` to `this.set( 'isOpen' );` in the "Property isOpen is set appropriately" test.

**Comment by azizpunjani** [comment]
@notmessenger please assign to me.

**Comment by notmessenger** [comment]
Closed by https://github.com/softlayer/sl-ember-components/pull/738
