### ISSUE TITLE
Refactor sl-modal-footer component

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#759]
* Remove `<div class="modal-footer">` from template
* Add support for `modal-footer` class in component

**Comment by SpikedKira** [comment]
modal-footer class is required by bootstrap to function as expected.  Please clarify.

**Comment by notmessenger** [comment]
The first sentence of http://guides.emberjs.com/v2.1.0/components/customizing-a-components-element/#toc_customizing-attributes:

> By default, each component is backed by a `<div>` element.

As such, the rendered HTML in the current configuration becomes:

```
<div>
    <div class="modal-footer">
        ....
    </div>
</div>
```

when it really can/should be:

```
<div class="modal-footer">
    ....
</div>
```

so if we remove `<div class="modal-footer">` from template and add the `modal-footer` class to the component per http://guides.emberjs.com/v2.1.0/components/customizing-a-components-element/#toc_customizing-class-names we can achieve the desired DOM structure.

**Comment by SpikedKira** [comment]
thanks for the clarification
