### ISSUE TITLE
Add missing properties to component

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#784]
Add these properties to the component with appropriate default values:

`name`
`readonly`

**Comment by erangeles** [comment]
@notmessenger please assign me this.

**Comment by erangeles** [comment]
http://softlayer.github.io/sl-ember-components/#/demos/sl-radio there is also a label property, it currently is not a property in the component. should that also be added to the list to add?

**Comment by notmessenger** [comment]
@erangeles Oh yes, it should be.
