### ISSUE TITLE
DEPRECATION: Set must be called with tree or four arguments; an object, a property key, a value and tolerant true/false

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#793]
When selecting either the "Fruit" or "Hex Code" headers.

**Comment by notmessenger** [comment]
Will be easier to work on after https://github.com/softlayer/sl-ember-components/pull/792 is merged

**Comment by azizpunjani** [comment]
@notmessenger this doesn't seem to be an issue anymore.

**Comment by notmessenger** [comment]
It still is at the `#/demos/sl-grid` url.

**Comment by azizpunjani** [comment]
Any reason I wouldn't be seeing it?

![image](https://cloud.githubusercontent.com/assets/156746/9934054/91d824b4-5d14-11e5-9940-bd9ad2887791.png)

![image](https://cloud.githubusercontent.com/assets/156746/9934020/659f9cec-5d14-11e5-9657-49be3c5e506e.png)

**Comment by notmessenger** [comment]
Start selecting the grid headers like in the issue description.

**Comment by azizpunjani** [comment]
@notmessenger was able to reproduce the error. Please assign this to me.

**Comment by azizpunjani** [comment]
Fixed by https://github.com/softlayer/sl-ember-components/pull/846
