### ISSUE TITLE
Refactor "spellcheck" property

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#802]
* is set to an invalid default value
* its list of acceptable values in the DocBlock do not align with supported values in the `enum`

**Comment by erangeles** [comment]
@notmessenger taking this as it's in tandem with #605.

**Comment by erangeles** [comment]
@notmessenger, this is no longer an issue, has been addressed already. https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/addon/components/sl-textarea.js#L98 https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/dummy/app/templates/demos/sl-textarea.hbs#L127 please move this into the done section of waffle.
