### ISSUE TITLE
"Align" enum is not showing up in generated documentation as expected

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#877]
https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/addon/components/sl-drop-button.js#L16

http://softlayer.github.io/sl-ember-components/docs/module-addon_components_sl-drop-button.html

**Comment by SpikedKira** [comment]
Need to remove @memberof then enum will show up in docs properly (tested).

Also consider adding @readonly
