### ISSUE TITLE
Update dependentKeys() test to follow new pattern

### ISSUE THREAD

**Issue by juwara0** [softlayer/sl-ember-components#892]
Update the dependentKeys() test to follow this pattern: https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/unit/components/sl-button-test.js#L159-L193 per https://github.com/softlayer/ember-style-guide/issues/36

**Comment by SpikedKira** [comment]
Seems to be done already:
https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/unit/components/sl-calendar-month-test.js

**Comment by notmessenger** [comment]
Previously addressed
