### ISSUE TITLE
Does _dependentKeys also work with Ember.observer()?

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#898]
* If so, create appropriate issues related to each component that should be tested
* Add a comment to https://github.com/softlayer/ember-style-guide/issues/35 noting the need for this as well

**Comment by erangeles** [comment]
@notmessenger please assign me this as all outstanding pull request reviews have been addressed.

**Comment by alxyuu** [comment]
it doesn't, right? I remember looking into this a while back and the only way I had to test it was to make sure the function was fired when the observed properties changed. That being said, that approach also walks the fine line of testing ember functionality, so....

**Comment by erangeles** [comment]
@alxyuu I will be conducting the R&D work on this tommorow on this issue and reporting my findings, my preliminary work on it has deemed `_dependentKeys` unsupported with `Ember.observer()` but will detail my findings once work is fully complete.

**Comment by erangeles** [comment]
addressed by https://github.com/softlayer/ember-style-guide/pull/69
