### ISSUE TITLE
Refactor "Backdrop is shown by default" Test

### ISSUE THREAD

**Issue by SpikedKira** [softlayer/sl-ember-components#903]
This should probably be replaced with the following tests:
- is backdrop option set to true by default?
- is backdrop VISIBLE when a modal is opened, specifying a backdrop?
- does the backdrop dom element not exist before test, but does after render the template (it was created by instantiating one or more modal components)?

**Comment by notmessenger** [comment]
The first bullet item will be addressed by https://github.com/softlayer/sl-ember-components/issues/765 instead of this issue's efforts, right?

**Comment by SpikedKira** [comment]
it will be tested in a different way in #765 the in accordance with other unit tests, but it is also tested here for now. (may be removed later since unit test will eventually cover it; but it is currently tested here)
