### ISSUE TITLE
sl-tab-pane add integration test for yielded content

### ISSUE THREAD

**Issue by azizpunjani** [softlayer/sl-ember-components#909]

**Comment by azizpunjani** [comment]
Verify content of pane matches what was passed to pane.

**Comment by notmessenger** [comment]
Should be addressed by https://github.com/softlayer/sl-ember-components/labels/sl-tab-pane

**Comment by juwara0** [comment]
I worked this issue into: https://github.com/softlayer/sl-ember-components/pull/1076
