### ISSUE TITLE
add name property to input based mixin

### ISSUE THREAD

**Issue by alxyuu** [softlayer/sl-ember-components#916]
the input based mixin needs to be updated to support the name property.

this will affect:
```
sl-checkbox
sl-input
sl-radio-group
sl-radio
sl-select
sl-textarea
```

**Comment by alxyuu** [comment]
@notmessenger can you assign this to me? I need the changes made for quicksilver

**Comment by erangeles** [comment]
@alyuu what's the status of this issue? I have issue #590 waiting on this issue to be completed. thanks

**Comment by alxyuu** [comment]
I'm still waiting on @notmessenger to do a final review
