### ISSUE TITLE
Upgrade broccoli-string-replace dependency

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#918]
to v0.1.0

**Comment by notmessenger** [comment]
Related to https://github.com/softlayer/sl-ember-components/issues/919

**Comment by azizpunjani** [comment]
@notmessenger please assign to me.

**Comment by notmessenger** [comment]
It is already assigned to me

**Comment by azizpunjani** [comment]
Ah OK, nvm then.
