### ISSUE TITLE
sl-grid footer is misaligned

### ISSUE THREAD

**Issue by azizpunjani** [softlayer/sl-ember-components#949]
![image](https://cloud.githubusercontent.com/assets/156746/10546533/1780af5a-73f4-11e5-8e6d-2416277e66f6.png)

Should look like this.

![image](https://cloud.githubusercontent.com/assets/156746/10546567/51853e8c-73f4-11e5-9208-dbbd0b3f444b.png)

**Comment by SpikedKira** [comment]
related to #795
