### ISSUE TITLE
Remove actions from sl-modal

### ISSUE THREAD

**Issue by SpikedKira** [softlayer/sl-ember-components#953]
hide() and show() actions don't seem to be used.  They both call method counter-parts which do get used.  There does not seem to be any reason to have the actions here.

**Comment by notmessenger** [comment]
@azizpunjani can you confirm this?

**Comment by azizpunjani** [comment]
@notmessenger confirmed, we do not need those actions in there. `open()` and `close()` methods are called by service, `show()`, `hide()` actions are not being used anywhere.

**Comment by azizpunjani** [comment]
@notmessenger confirmed, we do not need those actions in there. `show()` and `hide()` methods are called by service, `show()`, `hide()` actions are not being used anywhere.
