### ISSUE TITLE
Refactor DOM structure and supporting CSS and JS logic

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#974]
This came from the work done on https://github.com/softlayer/sl-ember-components/pull/956

Recommended solution from @SpikedKira: https://gist.github.com/SpikedKira/bd70f6a3b91f9d9249c5

**Comment by notmessenger** [comment]
Believe the suggested solution also pulls the footer up so that the "Viewing 6 of 6 Colors" text (in the demo grid, for example) does not get cut off when the details pane is displayed.

**Comment by SpikedKira** [comment]
This is dependent on #1125, #1033, #588, #398
