### ISSUE TITLE
Change class checking from filter() to hasClass()

### ISSUE THREAD

**Issue by notmessenger** [softlayer/sl-ember-components#975]
https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/integration/components/sl-modal-header-test.js#L14

https://github.com/softlayer/sl-ember-components/blob/EmberCli-1.13.8/tests/integration/components/sl-modal-footer-test.js#L14

**Comment by notmessenger** [comment]
Should be resolved by https://github.com/softlayer/sl-ember-components/pull/1020

**Comment by SpikedKira** [comment]
was resolved by #1020
